# Generated by Django 4.1.2 on 2022-11-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_client_company_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status_date",
            field=models.DateField(null=True),
        ),
    ]
