# Generated by Django 4.1.2 on 2022-11-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_order_status_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Interested",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
